### PR TITLE
Defer SoapClient creation

### PR DESCRIPTION
**Pull request by neclimdul**
For a couple reasons it is ideal to defer the creation of the SoapClient
until it is going to be used. In some cases it can lead to non-trivial
performance improvements.

1) SoapClient validates the WSDL during construction. When using using
the services you may accept the client/service as a dependency but only use it
occasionaly(caching etc). You will still take the performance hit even
when not used which should not happen in an IOC model.
2) Constructing SoapClient makes a web request which can throw a
SoapFault during construction. This is a very bad thing in general. It
can cause very frustrating failures outside try catch structures.
3) If you don't set the host there is an additional soap request during
construction even when the service isn't used.

### CODE REVIEW

**Comment by neclimdul** [comment]
This is sort of to alleviate issues like #58 and #32. It doesn't completely solve them because this library can't stop netsuite or connections to netsuite from being broken or slow at times but it tries to control where and when those errors happen.

**Comment by jrebs** [comment]
Hi, sorry about the delay on this. It sounds good enough but I want to give it a closer look and testing before rolling it in and I'd like to get that other 2020_1 release done now so I'm going to tag that new release first and then will get to this one in the next week or two. I have time off work coming up in August so I'll deal with it then at the very latest.

**Comment by jrebs** [comment]
Hi James, I hate to be a broken record but I again apologize for letting this sit so long. This has been quite a year of unexpected distractions, to which I'm sure we can all relate. I am absolutely going to address all outstanding pull requests by the end of 2020. I've just had a close look over this PR and I see no problems. I'll plug it into some working code tomorrow just to make sure I haven't missed anything (not saying I have any doubts in your work, I just feel it's important to have done so before pulling to master) and then merge it in. It will be available right away if you want to use dev-master but I will also tag a new release version once all the outstanding pull requests are resolved over the next week or two.

Thanks again.

**Comment by neclimdul** [comment]
No worries, I get how hard maintaining a project is :-D Let me know if there's anything I can do to help.

**Pull request merged**
