### PR TITLE
Make the generation process a little easier.

### PR DESCRIPTION
**Pull request by neclimdul**
Because I always have to figure this out... might as well provide some pointers in a composer script :-D

### CODE REVIEW

**Comment by jrebs** [comment]
Hi James, one issue here is that you're checking for the existence of the NetSuiteService.php file after already making a `require()` call on line 17 that results in a fatal bomb by composer before it can issue the helper dialog indicating the toolkit needs to be downloaded. Can you fix this up so that running `composer generate` without a toolkit in the expected location results in the controlled message intended?

Probably the simplest solution is to move the check up above the NsConfig.php require?

**Comment by jrebs** [comment]
Another thing is it seems like NetSuite has removed the public download page for the PHP Toolkit. The link that users to work for sample applications is gone now. It's not clear to me whether this is intended or an oversight, but this link (login required) contains a link to directly download the most recent toolkit distribution. 

https://netsuite.custhelp.com/app/answers/detail/a_id/24917

**Comment by neclimdul** [comment]
hmm, I see. I think you're right. I'll take a look.

Also.... that's troubling. I don't like that at all.

**Comment by jrebs** [comment]
> Also.... that's troubling. I don't like that at all.

Good news, it appears NetSuite has already fixed the broken link to the suitetalk sample apps.

**Comment by neclimdul** [comment]
Yeah that totally fails. not really sure how I tested that. Fixed.

**Pull request merged**
