### PR TITLE
Namespace array_is_associative

### LINKED ISSUE #72: PHP Fatal error:  Cannot redeclare array_is_associative()
Hi, We are getting this error

PHP Fatal error:  Cannot redeclare array_is_associative() (previously declared in /var/www/html/vendor/weew/helpers-array/src/array.php:328) in /var/www/html/vendor/ryanwinchester/netsuite-php/src/includes/functions.php on line 29

### PR DESCRIPTION
**Pull request by neclimdul**
This is a pretty generically named function that can conflict with code
from other projects when left in the global namespace.

Fixes #72

### CODE REVIEW

**Comment by neclimdul** [comment]
If you review without whitespace changes the actual difference is more clear.

**Comment by jrebs** [comment]
> If you review without whitespace changes the actual difference is more clear.

Thanks for this tip. I honestly never even noticed that option before you mentioned it.

**Comment by ezequiel9** [comment]
Hey @jrebs I know this is not related to this package but I am a bit frustrated trying to generate the TBA Header to use the Rest API. The header must be generated following the steps in the docs but I can't make it work for POST requests. Have you done that? maybe you already did it and have some code somewhere :) thanks.

**Comment by jrebs** [comment]
@ezequiel9 Sorry, I've never worked with the NetSuite REST API, I only have experience with the soap web services. Feel free to open a separate issue and provide some more detailed examples and maybe I or someone else can identify what might be wrong.

**Comment by ezequiel9** [comment]
Perfect, Thank you very much! I'll post one tomorrow! :)

**Pull request merged**
